In [319]:
import numpy as np
import pandas as pd
import csv

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
import spacy


nlp = spacy.load("en_core_web_sm")
X_train = []
Y_train = []
numerical_categories={}
# open .tsv file
with open("train_topics_keywords.tsv", encoding='utf-8') as file:
       
    # Passing the TSV file to reader() function with tab delimiter. This function will read data from file
    tsv_file = csv.reader(file, delimiter="\t")
    # printing data line by line
    for line in tsv_file:
        Y_train.append(line[1])
        X_train.append(line[2])

for i in range(len(X_train)):
    numerical_categories[Y_train[i]] = i
Y_train = list(numerical_categories.keys())


In [186]:
data = {"XTrain":X_train,"YTrain":Y_train}
df = pd.DataFrame(data)
df

XTrain  YTrain
0   cultivated,agricultural,maize,corn,fruit,wheat...       0
1   reptile,lizard,salamander,fossil,frog,prehisto...       1
2   astronomer,astronomy,astrophysicist,mathematic...       2
3   aviation,airfield,airport,aerospace,aircraft,s...       3
4   actor,cast,screenwriter,filmmaker,film,actress...       4
5   singer,musician,songwriter,guitarist,frontman,...       5
6   philosopher,scientist,mathematician,physicist,...       6
7   bird,island,plumage,falconidae,pheasant,wildli...       7
8   novel,trilogy,paperback,miniseries,folklore,bo...       8
9   financier,businessman,roosevelt,richest,forbes...       9
10  pharmacology,sulfur,sulfuric,sulfurous,medicat...      10
11  charlemagne,cathedral,pope,babylon,gothic,hymn...      11
12  hamburg,london,berlin,kyiv,riga,lviv,guangzhou...      12
13  composer,musician,piano,libretto,concerto,orch...      13
14  programming,java,computing,compiler,programmer...      14
15  software,macromedia,multimedia,freeware,micros...      15
16  cricket,batsman,bowler,wicket,fielding,cricket...      16
17  convicted,mp,homicide,fbi,murderer,criminal,in...      17
18  cyclist,cycling,giro,racing,competed,vuelta,ri...      18
19  hydroelectric,hydroelectricity,dam,river,flood...      19
20  engineer,computer,hardware,engineering,worksta...      20
21  screenplay,film,cartoon,cast,comic,musical,sou...      21
22  mahabharata,prussia,baltic,slavic,charlemagne,...      22
23  sea,valley,river,gulf,ocean,oceanic,coastline,...      23
24  slavery,enslaved,slave,klan,constitution,mamlu...      24
25  insect,larva,mosquito,larval,pest,wasp,parasit...      25
26  muhammad,muslim,caliph,prophet,quran,caliphate...      26
27  japan,japanese,tokyo,nikkei,meiji,tokugawa,nik...      27
28  japanese,nippon,takashi,akihito,aoki,japan,nar...      28
29  judah,jewish,judaism,jerusalem,testament,judea...      29
30  hindi,bengali,marathi,arabic,indian,syriac,kan...      30
31  novelist,literature,writer,poetry,romanticism,...      31
32  medication,pharmacology,herbal,herb,stimulant,...      32
33  prussia,mamluk,mamluks,mameluk,mamlukization,p...      33
34  regiment,regimental,jacobite,infantry,brigade,...      34
35  admiral,naval,captain,fleet,navy,seaman,ensign...      35
36  motorsport,racing,prix,motorsport,motorsports,...      36
37  ruud,eindhoven,arubans,aruba,aruban,arubano,ve...      37
38  photographer,camera,photographic,photography,p...      38
39  diplomat,constituency,politician,representativ...      39
40  ski,skiing,olympics,olympic,skier,medalist,med...      40
41  cambodia,thai,myanmar,thailand,burmese,lao,vie...      41
42  cartoon,cast,itv,acting,actress,actor,spongebo...      42
43  tennis,wimbledon,federer,djokovic,nadal,novak,...      43
44  trains,railway,rail,railroad,tramlink,crossrai...      44
45  video games,arcade,gaming,nintendo,sega,playst...      45

In [250]:
from sklearn.feature_extraction.text import TfidfVectorizer
# vectorizer = CountVectorizer(stop_words='english')
X_Ai =  [
     'This is the first document cheese.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first time?',
 ]
Y_Ai = [1,2,3,4]
vectorizer = TfidfVectorizer(stop_words='english')
# features__=vectorizer.fit_transform(words)
bow_vectorizer = CountVectorizer()
bowVect = bow_vectorizer.fit(X_Ai)
bowTrain = bow_vectorizer.transform(X_Ai)
bow_vectorizer.get_feature_names_out()

# def cos_similarity(textlist):
#     tfidf = TfidfVec.fit_transform(textlist)
#     return tfidf
# data = {'features':features__,
#         'target': categories}
# df = pd.DataFrame(data)

array(['and', 'cheese', 'document', 'first', 'is', 'one', 'second', 'the',
       'third', 'this', 'time'], dtype=object)

In [225]:
print(bowTrain.toarray())

[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [129]:
features_= []
for i in df['features']:
    features_.append(cos_similarity(i))


In [251]:
knn = KNeighborsClassifier(n_neighbors=1)
# training our classifier ; train_data.target will be having numbers assigned for each category in train data
clf = knn.fit(bowTrain, Y_Ai)

In [255]:
res=clf.predict(bow_vectorizer.transform(["second"]))
print(res)

[4]


In [258]:
5*"s"


'sssss'

In [323]:
#X_TRAIN INTO ONE LONG LIST
categories_repeats=[]
print(numerical_categories)
for x in range(len(X_train)):
    l = len(X_train[x].split(","))
    #print(l,X_train[x])
    lst = l*(numerical_categories[x]+",")
   # print(len(lst.split(",")))
    categories_repeats.append(lst[:len(lst)-1])

Y_testing_train = ",".join(categories_repeats).split(",")
X_testing_train = ",".join(X_train).split(",")
data_test = {"x":X_testing_train, "y":[numerical_categories[y] for y in Y_testing_train]}
df_test = pd.DataFrame(data_test)
df_test


{'Agriculture': 0, 'Amphibians and Reptiles': 1, 'Astronomy': 2, 'Aviation': 3, 'Biography/WikiProject Actors and Filmmakers': 4, 'Biography/WikiProject Musicians': 5, 'Biography/science and academia work group': 6, 'Birds': 7, 'Books': 8, 'Business': 9, 'Chemicals': 10, 'Christianity': 11, 'Cities': 12, 'Classical music': 13, 'Computer science': 14, 'Computing': 15, 'Cricket': 16, 'Crime and Criminal Biography': 17, 'Cycling': 18, 'Dams': 19, 'Engineering': 20, 'Film/American cinema task force': 21, 'Former countries': 22, 'Geography': 23, 'Human rights': 24, 'Insects': 25, 'Islam': 26, 'Japan': 27, 'Japan/Biography task force': 28, 'Jewish history': 29, 'Languages': 30, 'Literature': 31, 'Medicine': 32, 'Middle Ages': 33, 'Military history': 34, 'Military history/Maritime warfare task force': 35, 'Motorsport': 36, 'Netherlands': 37, 'Photography': 38, 'Politics': 39, 'Skiing and Snowboarding': 40, 'Southeast Asia': 41, 'Television': 42, 'Tennis': 43, 'Trains': 44, 'Video games': 45}


KeyError: 0

In [301]:
print(len(Y_testing_train),len(X_testing_train))

2898 2898


In [307]:
vectorizer = TfidfVectorizer(stop_words='english')
# features__=vectorizer.fit_transform(words)
bow_vectorizer = CountVectorizer()
bowVect = bow_vectorizer.fit(X_testing_train)
bowTrain = bow_vectorizer.transform(X_testing_train)
bow_vectorizer.get_feature_names_out()

array(['aachen', 'abbasid', 'abbasids', ..., 'zoologist', 'zvonereva',
       'ʿalī'], dtype=object)

In [316]:
knn_test = KNeighborsClassifier(n_neighbors=1)
# training our classifier ; train_data.target will be having numbers assigned for each category in train data
clf_test = knn.fit(bowTrain, Y_testing_train)
res=clf_test.predict(bow_vectorizer.transform(["farm", "chicken","land",",manchester","milan","westminster","maize,corn,fruit,wheat,agriculture",",constitution,mamluk,","takashi"]))
print(res)

['Business' 'Agriculture' 'Business' 'Cities' 'Cities' 'Cities'
 'Agriculture' 'Human rights' 'Japan/Biography task force']


In [343]:
import numpy as np
import pandas as pd
import csv
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier

X_train_temp = [] 
Y_train_temp = []

categories_repeats=[]
numerical_categories={}

with open("train_topics_keywords.tsv", encoding='utf-8') as file: #load tsv
       
    # Passing the TSV file to reader() function with tab delimiter. This function will read data from file
    tsv_file = csv.reader(file, delimiter="\t")
    # printing data line by line
    for line in tsv_file:
        Y_train_temp.append(line[1]) # targets
        X_train_temp.append(line[2]) # words related to a target


for i in range(len(X_train_temp)):
    numerical_categories[i] = Y_train_temp[i] # Assigning category a number
Y_train_temp = list(numerical_categories.keys())

for x in range(len(X_train_temp)):
    l = len(X_train_temp[x].split(","))
    lst = l*(numerical_categories[x]+",")
    categories_repeats.append(lst[:len(lst)-1])

X_train = ",".join(X_train_temp).split(",")
Y_train = ",".join(categories_repeats).split(",")

data = {"X_train":X_train,
"Y_train":Y_train}


bow_vectorizer = CountVectorizer(stop_words="english")
bowVect = bow_vectorizer.fit(X_train)
bowTrain = bow_vectorizer.transform(X_train)
bow_vectorizer.get_feature_names_out()

knn = KNeighborsClassifier(n_neighbors=1)
# training our classifier ; train_data.target will be having numbers assigned for each category in train data
clf = knn.fit(bowTrain, Y_train)
res=clf.predict(bow_vectorizer.transform(["window","sulfuric","hill","wimbledon", "falconidae wii"," computer science"]))
print(res)

['Computing' 'Chemicals' 'Business' 'Tennis' 'Birds' 'Computer science']
